const Constants = {
  LOAD_POKEMONS_REQUEST: 'LOAD_POKEMONS_REQUEST',
  LOAD_POKEMONS_SUCCESS: 'LOAD_POKEMONS_SUCCESS',
  LOAD_POKEMONS_FAIL: 'LOAD_POKEMONS_FAIL',
  LOAD_CHARACTERISTICS_REQUEST: 'LOAD_CHARACTERISTICS_REQUEST',
  LOAD_CHARACTERISTICS_SUCCESS: 'LOAD_CHARACTERISTICS_SUCCESS',
  LOAD_MORE_REQUEST: 'LOAD_MORE_REQUEST',
  LOAD_MORE_SUCCESS: 'LOAD_MORE_SUCCESS'
};

export default Constants;
